### ISSUE TITLE
how to declare and work on multiple element?

### ISSUE THREAD

**Issue by ghost** [TestCentricity/testcentricity_web#11]
I am not able to declare the element which is returning the more than 1 element.
e.g. 
xpath = a[class*='card'] which identified the 20 similar elements in dom. 

so in selenium I can use the below stmt to work with 

List<WebElement> elementName = driver.findElements(By.LocatorStrategy("LocatorValue"));

Similarly, how to handle this situation in TestCentricity_Web / TestCentricity. 

Please guide.

**Comment by ghost** [comment]
@TestCentricity 

Please have a look into it immediatly

**Comment by TestCentricity** [comment]
TestCentricity does not have an equivalent to Selenium's `driver.findElements` method.

**Comment by ghost** [comment]
@TestCentricity - Any other solution ?
