### ISSUE TITLE
Got "NoMethodError" when calling below method.

### ISSUE THREAD

**Issue by ghost** [TestCentricity/testcentricity_web#9]
Error : 
NoMethodError: undefined method `each' for nil:NilClass
from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/testcentricity_web-4.0.3/lib/testcentricity_web/web_core/page_objects_helper.rb:25:in `verify_ui_states'

Code Block :

`def verify_user
    roles = {
     ** Some Roles **
    }
    ui = {
      ** Some UI element validation **
    }
    ui[change_role_button] =  if true
                                                       stmt 1
                                              else 
                                                      stmt 2
                                              end
                         avatar_ui = if true
                                                    stmt 1
                                            else 
                                                    stmt 2
                                            end
    # verify that user information is correctly displayed
    verify_ui_states(avatar_ui.merge(ui))
  end`

**Comment by TestCentricity** [comment]
* Current version of `testcentricity_web` is v4.2.6.
* Required version of Ruby is >= 2.7.5.
* Your code snippet does not specify whether your `verify_user` method is defined within the context of a `PageObject` or `PageSection`.
* Your code snippet does not specify what the actual values are for:
  - `** Some UI element validation **`
  - `stmt 1`
  - `stmt 2`
 
If error is still occurring after upgrading `testcentricity_web` and Ruby, then please include a more detailed code block for further analysis. Without knowing what you are attempting to pass in to `verify_ui_states` method, and the context, we cannot determine a reason for the error you are encountering.

**Comment by ghost** [comment]
it was the issue with some null value in the hash.
